### ISSUE TITLE
Improved OnBoarding experience / documentation

### ISSUE THREAD

**Issue by NPadrutt** [BlazorFluentUI/BlazorFluentUI#138]
I think you guys did a great job with this library. What I think could be improved is the onboarding experience for new users. For one I think the installation instructions in the ReadMe is not up to date / not the same as the one in the wiki.
Also, while the demo app is great and very helpful, I think it would make things much easier if there where a proper API documentation ideally directly paired with the demo.
For comparison here are two, in my opinion very well done examples:
- MatBlazor (https://www.matblazor.com/) 
- ant-design-blazor (https://append-it.github.io/ant-design-blazor/).

Since both are open source including the documentation page, we maybe could one of those take as a starting point. My knowledge about UI development / Web UI Development is very basic, but I'm glad to help out where I can with this.

**Comment by Eweol** [comment]
@NPadrutt Hey,
You are right with some points and we also have it on our list but we do that on freetime, and I that's why we first focused on features and toke the demo applications as API documentation
If you want You can start improving this and send us as PR.
We are very happy about everybody which can help us

**Comment by NPadrutt** [comment]
@Eweol yeah I totally understand that. 
I'm playing around with some ideas, but so far I'm not sure what the smartest way to go is. Let me know if you have something in mind.

**Comment by Eweol** [comment]
One of my first ideas for document api was to use the RichTextEditor in readonly mode for code snippets over or under the Component which is related to the code snipped but I'm not an UX/UI guy XD

**Comment by NPadrutt** [comment]
Then we have the same problem ;)
Maybe the easiest is just throw the code in a div and format it with [bootstrap code ](https://getbootstrap.com/docs/4.0/content/code/). I will try that out.

**Comment by limefrogyank** [comment]
@NPadrutt

**Comment by limefrogyank** [comment]
@NPadrutt

**Comment by limefrogyank** [comment]
Sorry, didn't realize Telegram would @ you without showing anything in the issue...

![image](https://user-images.githubusercontent.com/7821384/81982991-7e780400-95e7-11ea-8c7d-d0b0234b7f07.png)


![image](https://user-images.githubusercontent.com/7821384/81982963-7324d880-95e7-11ea-8692-cce881dcf5e7.png)

**Comment by NPadrutt** [comment]
@limefrogyank  I really like that!

**Comment by limefrogyank** [comment]
I can push it to the master demo code since it's not really affecting anything in the library.  We can play with it if the styling isn't perfect (maybe the header font size).  As far as implementing it in a large scale way, we should make it a component because it requires some code for the open/close and label.  For the contents, should we use a GitHub API or just copy and paste the contents?  Working with literal strings in razor files is really annoying so it would be nice to just get the string from GitHub by line or something.

I'll push this piece now.  It's only in buttonPage

**Comment by limefrogyank** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7821384/81983876-e4b15680-95e8-11ea-85e3-06c3a585b6fa.gif)

**Comment by NPadrutt** [comment]
yeah a component would be nice I think. Also might make for a nice expander component in general? I  for one could actually need such a component in a project I want to migrate to Fluent.

Instead of getting the file via the GitHub API I think it would be easier to just read the local one who comes on deployment. That way we don't have to handle a REST call. We would have to find a way to strip out the relevant part of the file. but maybe there is a way to make a placeholder component.

I think the way they do it in the ant repository I linked initially is by having a "Codebox" component which holds a description and a Demo.  Then they just render that via RenderFragment and also create that as a Type and put the Demo as Sample Code in. At least if I understood that correctly from looking at it / debugging it.

**Comment by limefrogyank** [comment]
Ah, I think I see now.  It's a pretty good trick.  They added the following to csproj to copy their razor files into temporary metadata files:
```
    <Message Text="Copying the README.md file to the wwwroot/docs folder." Importance="High" />
    <Copy SourceFiles="@(Readme)" DestinationFolder="$(ProjectDir)\wwwroot\docs" />
    
    <Message Text="Copying the example files to the wwwroot/examples folder." Importance="High" />
    <Copy SourceFiles="@(Examples)" DestinationFiles="$(ProjectDir)wwwroot\examples\%(RecursiveDir)%(Filename).md" />
``` 
And then read those files as strings and just display them as the "example code".  Their organization is good because they can pull the code by the demo file name.  We have all the demos for one component all in one razor file, so it will be tricky to pull out the relevant code pieces.  Might have to think about if there's an easier way to do this without having to separate all of our demo pieces into different components.

**Comment by NPadrutt** [comment]
Would be separating them such a big deal? Maybe I underestimate the effort as of now. But might help with maintainability in the long run.

**Comment by limefrogyank** [comment]
I guess not.  I'll see about starting this soon...

**Comment by NPadrutt** [comment]
I tried already once to build that solution into the demo project, but wasn't quite successful. I'll see if I can give it another go over the weekend. Otherwise, if by then you already managed to solve that give me a note. Then I can help you with the grind of separating the components.

**Comment by limefrogyank** [comment]
I figured it out... it's a little hacky since I used relative paths, but the client-side demo now generates .md files in the wwwroot/examples folder post-built. (Ignored by git)

**Comment by limefrogyank** [comment]
Oh, actually, there's a branch where @Eweol has been renaming components.  That's probably where it should be done.  I'm not sure how far he has gotten.

**Comment by Eweol** [comment]
@limefrogyank I'm ready with it I only want that you also have a look at it 😉

**Comment by NPadrutt** [comment]
Is that the branch FluentUI_renaming?

**Comment by limefrogyank** [comment]
We've got a solution in progress now. It doesn't require separating the pieces of the demo pages even. Take a look at the buttonsPage in the renaming branch

**Comment by NPadrutt** [comment]
Sounds good. I'll have a look at it later! :)

**Comment by NPadrutt** [comment]
It took a bit longer till I had time. I really like it. What I would change is show the code below the actual control. If that is okey with you, I would start use the Demo control on more pages and add a PR to the name branch.

**Comment by limefrogyank** [comment]
I'm okay with the code below the control.  It would be easy to change back if there's suddenly a reason to revert anyways.

**Comment by vnbaaij** [comment]
In V5 all pages in the Demo site have code samples now
