### ISSUE TITLE
Add "ChoiceGroup" Component

### ISSUE THREAD

**Issue by StevenRasmussen** [BlazorFluentUI/BlazorFluentUI#147]
I think adding this component would be a nice addition.  I am looking to contribute and think that this would be a great place for me to get familiar with the project.  I wanted to make sure that someone else wasn't already working on this before I get started though.  Please let me know if you would accept a contribution in this area.  Thanks!

**Comment by limefrogyank** [comment]
We'd be happy to have this component added.  FYI, we will soon be merging a branch called refactor/FluentUI_renaming to master.  It's a big breaking change because we're changing the name of the namespace to BlazorFluentUI instead of BlazorFabric because of the the name change at Microsoft.  Also, because you can't alias any of the component names, we decided to add the BFU* prefix to all the component names.  This one is a hard one to swallow, but it makes sense.  We were having a lot of name collisions and just namespace prefixing everything was not the best solution.  MatBlazor does this, too.

So it's fine to work in master, just be aware of the new naming scheme...
