### ISSUE TITLE
Demo site is extremely slow to respond to navigation

### ISSUE THREAD

**Issue by davidnmbond** [BlazorFluentUI/BlazorFluentUI#157]
The demo site here:
[https://www.blazorfluentui.net/](https://www.blazorfluentui.net/)
...is extremely slow to respond to navigation events in Chrome.

**Comment by limefrogyank** [comment]
There are certain pages that are slower to load... but if you switch between Checkbox page and Label page, it's pretty fast for me.  Dropdown page is slower and Calendar is pretty slow to load, I agree.  Partly it's due to how we're loading styles... and we're trying some optimizations.

GroupedList is really slow!  But there is no threading in Blazor wasm yet and that page is doing some sorting and grouping before it can finish loading the UI.  I won't swear that the code is well optimized, but it's partly due to the fact there is no multithreading yet.

**Comment by davidnmbond** [comment]
Hi @limefrogyank,

This is UI - "lack of multithreading" is certainly **not** the issue.

I'd love to use this library in my project, but the demo site is so unusably slow.  Unfortunately - anyone visiting the demo site would be immediately put off.

The world needs this project - please review what is taking so long and spend some time on performance improvements!

**Comment by limefrogyank** [comment]
See if it's faster for you now:
https://www.blazorfluentui.net/

**Comment by las3r** [comment]
It's faster, but by no means comparable to the neighbours at blazor boilerplate. (Client-side demo: https://blazor-wasm.quarella.net/). Navigation between different pages is nearly instant. Yes they'll be slower once you put loads of components, but MatBlazor has shown that it is possible to have a very reactive UI experience (https://www.matblazor.com/List). I'm not sure what the different is, but _every_  click on the blazorfluentui is taking 1+ second to load, at the very least it's annoying.

I'm trying to understand where the speed decrease comes from, because you are basically wrapping the O365 Fluent UI with razor components (much like MatBlazor does with material UI).

**Comment by NPadrutt** [comment]
>  I'm not sure what the different is, but every click on the blazorfluentui is taking 1+ second to load, at the very least it's annoying.

That statement makes me curious. For me there are certain pages a bit slow to load (around a second). That is mostly for the lists. Once they are loaded they react very responsive for me. So I'm not sure if that is an exaggeration or if things like buttons and choicegroups really take a second or more to react for you.

As a sidenode: the link to the mat blazor page  (https://www.matblazor.com/List) is server side blazor and not wasm.

**Comment by vnbaaij** [comment]
Not a problem anymore. Demo is lighting fast now.
