### ISSUE TITLE
DetailList does not work on Safari (it does now, but with side-effects)

### ISSUE THREAD

**Issue by NPadrutt** [BlazorFluentUI/BlazorFluentUI#176]
It seems there is an issue with the details list on safari. As far as I can see it doesn't work on either MacOS in Safari, nor iOS or iPadOS.
This is how my view should look like:

<img width="1126" alt="Screenshot 2020-06-23 at 08 32 20" src="https://user-images.githubusercontent.com/1764367/85368808-3a541980-b52c-11ea-8e3f-6bba1fb535a7.png">

And this is how it actually does look like:

<img width="923" alt="Screenshot 2020-06-23 at 08 32 00" src="https://user-images.githubusercontent.com/1764367/85368839-450eae80-b52c-11ea-91d9-ad434c932603.png">

The only thing in terms of error I can see is this message on the console:

<img width="1243" alt="Screenshot 2020-06-23 at 08 35 58" src="https://user-images.githubusercontent.com/1764367/85369042-a171ce00-b52c-11ea-94ed-302b81deb2bd.png">

EDIT: I did some investigating. Here is the position in the code the error occurs. 

<img width="1029" alt="Screenshot 2020-06-23 at 13 35 54" src="https://user-images.githubusercontent.com/1764367/85399095-89af3f80-b556-11ea-8098-d88e89f778e1.png">

**Comment by limefrogyank** [comment]
Mostly fixed with #177 

However, there is a small side-effect on iOS iPad (not MacOS and not iOS iPhone!).  The polyfill seems to delay other rendering.  Scroll the nav menu on any page but one that contains a List... and it scrolls fine.  Then pick a List containing page.  Now scroll the nav menu and there is a slight delay in rendering the rest of the NavLink components
