### ISSUE TITLE
Panel with DropDown in it closes when selection changes for the first time

### ISSUE THREAD

**Issue by NPadrutt** [BlazorFluentUI/BlazorFluentUI#179]
I have a Panel with this drop down in it:

```
            <BFUDropdown ItemsSource=@RoleOptions
                         Label=@Localizer["RoleLabel"] />
```

When I now change the selection of the Dropdown for the first time the panel closes. When I open it again it stays open on the subsequent selection changes. Light dismiss is disabled, so that doesn't have an influence.

**Comment by NPadrutt** [comment]
I did some further digging and I have to say I'm kinda confused. I use the DropDown Control on another page as well within a panel and there it works as expected. I tried to align the one with the problem as closely as possible but the issue still persists.

**Comment by NPadrutt** [comment]
After more investigations I found out, that the issue seems to be with the OnDismiss event. This is fired when an item is selected. When I don't set a binding to an event or an empty event the selection works as expected. That was the reason why it worked on my other screen, since I forgot to set this. Now that I have set the OnDismiss event it has the same behaviour as well.

**Comment by limefrogyank** [comment]
I'm narrowing down what is happening... it's either a failure in how `BFULayer` works or there's a conflict between `BFUFocusTrapZone` in the panel and `BFUFocusZone` in the dropdown.    I've got to teach a class in 30 minutes so I'll come back to it this evening...

**Comment by limefrogyank** [comment]
Yes, it's a failure of BFULayer.  The way Panel works is to detect clicks outside of the Panel.  Normally that's just the Overlay area.  The overlay is technically a child of Panel, so the javascript code detects that and then does `preventDefault()` so that the click stops propagating. 

However, a Dropdown's popup window is *not* technically a child of the Panel.  It uses a Layer which sends the contents of the popup to the LayerHost (near the root of the app).  So it propagates the mouseclick and unexplained things happen... like the dismiss.  

However, the React version of Layer is an abstraction of react Portals.  Portals do the same thing... they put elements somewhere else in the document... but the advantage is that they remain children of their parents.  Our version of Layout doesn't do that.  I need to fix that.

**Comment by limefrogyank** [comment]
Solved it!  What a pain in the butt.  React FluentUI stores information about the virtual parent on the element itself but we can't do that in Blazor as Blazor will constantly recreate the element via render process.  I had to use a combination of data- attributes and a dictionary stored in javascript to maintain the relationships between virtual parent and child.

**Comment by limefrogyank** [comment]
#183 Fixes this!

**Comment by NPadrutt** [comment]
wow, that really sounds like a huge pain. Good job!
