### ISSUE TITLE
Limit the number of charactors within RichTextField and remove the image picker button

### ISSUE THREAD

**Issue by toklive** [BlazorFluentUI/BlazorFluentUI#201]
What would be the easiest way to implement character limit validation with the RichTextEditor control? Also, need to hide the image button on the control. Thanks for your help!

**Comment by limefrogyank** [comment]
You'll have to implement it yourself.  I wrote it more as a demo.  While it's certainly usable as-is, you can't customize it... and I didn't write any customization features because there are just so many ways people would want to customize it.  (Just take a look at any of the popular javascript rich text editors.) 

https://github.com/BlazorFluentUI/BlazorFluentUI/tree/master/src/BlazorFluentUI.BFURichTextEditor

So take a look at the source and pay attention to the javascript file inside the wwwroot folder.  That's got all the inner working of how I made each button work.   I would have used typescript, but quill.js has a bunch of samples written in plain javascript and I didn't want to build from npm packages just to write in typescript.  

 The C# code-behind file has a bunch of timer stuff that lets blazor and quill sync what they think is inside the editable div.  I would keep all of that the same and just change the UI buttons.

As for character limits... I think you can watch the `RichTextChanged` callback and do something with it.
