### ISSUE TITLE
OnColumnContextMenu on DetailsList

### ISSUE THREAD

**Issue by bobonic** [BlazorFluentUI/BlazorFluentUI#210]
How to implement ContextMenu on DetailList

![image](https://user-images.githubusercontent.com/2681829/94430755-fde92700-01c6-11eb-882f-452f8176a8fa.png)

**Comment by limefrogyank** [comment]
Very advanced scenario!  You can follow the DetailsList demo page, but instead of changing the sort based on `OnColumnClick`, you can open a Dropdown and react to the choices inside the dropdown instead.  Remember, for the basic DetailsList, you have to do all the sorting yourself.  The column header properties are just labels.  You turn them on to indicate on the UI that the column is sorted.  You still have to sort your data.

(You don't have to use DynamicData.  I like it for the way it automates a lot of things, but you can do it all manually, too.)

For the upcoming .Net5 release, I'm hoping to release a version of DetailsList that will dynamically change the sort based on the properties.  You won't have to sort any of the data yourself.
