### ISSUE TITLE
BFUCommandBar: Features don't work

### ISSUE THREAD

**Issue by datarit** [BlazorFluentUI/BlazorFluentUI#218]
I'm testing the functionality of the BFUCommandBar, and when setting BFUCommandBarItem.Href or BFUCommandBarItem.ItemType nothing happens.

**Comment by limefrogyank** [comment]
I can see that Href wasn't wired up.  It must have been an early implementation and button hadn't yet been setup to do `<a>` tags.  That's easy to fix.

ItemType... looks like it was meant to create a divider.  That doesn't work... at least not in the main bar.  But it should work when it gets moved to the overflow menu since we have that working in dropdowns.  Ok, something else to fix.

**Comment by limefrogyank** [comment]
Actually, `itemType` on the original React component was never meant to do anything on the CommandBar itself.  We do have parity with the react component.  I can see that this might be a nice addition though.  The commandbaritems have to inherit `IContextalMenuItem` because they go into the overflow menu and get rendered as a contextual menu sometimes, but where not meant to be used the same way on CommandBar.  

We do not have a template override for CommandBarItem though.  That might be something else we can add so that you can design your own divider.

(The Href missing is still bad though.)

**Comment by limefrogyank** [comment]
As a workaround, you can implement your own CommandBar.  All you would have to do it add another conditional to the `ItemTemplate` section (in the primary area) to check for the ItemType and render something different.
https://github.com/BlazorFluentUI/BlazorFluentUI/blob/master/src/BlazorFluentUI.BFUCommandBar/BFUCommandBar.razor#L15

**Comment by vnbaaij** [comment]
HRef has been implemented (long time ago already). ItemType workaround is alreay implemented in CommandBarPage
