### ISSUE TITLE
Setting selection without items results in NullReferenceException

### ISSUE THREAD

**Issue by GeertvanHorrik** [BlazorFluentUI/BlazorFluentUI#233]
1. In my blazor app, I set some parameters (including ItemsSource, which is null at this point).
2. I am not using selection (even explicitly disabled it with the selection zone property)

Then I get a NullReferenceException.

Probably here:

https://github.com/BlazorFluentUI/BlazorFluentUI/blob/master/src/BlazorFluentUI.BFUDetailsList/BFUDetailsList.razor.cs#L190

I think there should be:

1. No code running at all when selection is disabled
2. Check if ItemsSource is null before adding it to the selection

**Comment by limefrogyank** [comment]
Good idea.  I had overlooked that `DisableSelectionZone` parameter and forgot to account for null items.  I'll add those fixes.

**Comment by limefrogyank** [comment]
Turns out it was a little more than just the selection problem.  BFUList will crash if  `ItemsSource` is null.  This is actually because I'm using Blazor's `Virtualize` component as a basis for it and even that will throw an exception in a similar situation.  The fix involves having a backing field for ItemsSource that is never null, only an empty list if we try to set it null.

I don't think that will have any side-effects, but I'm not positive.  It seems to work.  `BFUDetailsListAuto` doesn't suffer from the same problem because it's not using `ItemsSource` directly for anything.  That gets parsed by `DynamicData` into a readonly list that is never null.

**Comment by limefrogyank** [comment]
Fixed with https://github.com/BlazorFluentUI/BlazorFluentUI/commit/0965df5c23b4a4873b40c3271c1d5324bb3607fa hopefully.

**Comment by GeertvanHorrik** [comment]
Just checked the PR, looks great!
