### ISSUE TITLE
[Question] Use OnClick without breaking parent BlazorFuentUI OnClick

### ISSUE THREAD

**Issue by Ralms** [BlazorFluentUI/BlazorFluentUI#248]
Hi there, 

I want do some some actions when the user clicks on a NavLinkGroup, however when I define OnClick, it breaks the collapse functionality. 

Here is an example of what I'm doing: 
```
<BFUNav>
    <BFUNavLinkGroup Name="Link Group Title" OnClick=@(() => LinkGroupOnClick())>
    </BFUNavLinkGroup>
</BFUNav>
```

I was about to submit a Pull Request to add functionalities such as adding visibility on the current collapse state and ability to define a OnClickCallback, but tough about asking first.

Also, can we enable "Discussions" on this repository so we don't have open issues for questions :)  ?

**Comment by Ralms** [comment]
So, after playing around with the code, I've found out that in BFUNavLinkGroup, inside the ClickHandler method, instead of calling await OnClick.InvokeAsync(this), calling await OnClick.InvokeAsync() fixed it. 
Essentially removing the parameter and reference to the component. 

However, I don't know 100% why do we need to reference the NavLinkGroup component in this case.

**Comment by limefrogyank** [comment]
Discussions are enabled now!  I didn't really know that existed.  

```
<BFUNavLinkGroup Name="First" CollapseByDefault="false" OnClick=@((group) => debug = $"This link was clicked")>
...
</BFUNavLinkGroup>
```
This works for me and will set my `string debug` with that text.  The `group` parameter lets you write a generic event handler that can react to clicking on any group...  

I will admit that the decisions about how all of these components were implemented were not all correct.  It's true that it would have been better to make some type of `GroupClickedArgs` class and return that, but at the time it seemed that returning the actual instance of the group was fine since it included all of the parameters you would need to identify which group was clicked.

I would avoid introducing changes that would break things for users unless it's really necessary... i.e. fixes a terrible bug or improves performance greatly.  Maintaining some parity with the react components also makes this library a worthwhile (hopefully) alternative for when you want to use blazor.

**Comment by limefrogyank** [comment]
```
<BFUNavLinkGroup Name="First" CollapseByDefault="false" OnClick=@GroupClicked>
...
</BFUNavLinkGroup>

@code{
string debug="";

public Task GroupClicked(BFUNavLinkGroup group)
{
    debug = $"The {group.Name} group was clicked.";
}
}
```

**Comment by vnbaaij** [comment]
The question was answered. Closing this now.
