### ISSUE TITLE
BFUList and Grid Layout Clarification

### ISSUE THREAD

**Issue by DerekChasse** [BlazorFluentUI/BlazorFluentUI#251]
Does the BFUList implementation support the grid style layout that is shown on the official FluentUI site?

https://developer.microsoft.com/en-us/fluentui/#/controls/web/list

There seems to be an ItemSize feature, which looks like it's relevant to when the list is Virtualizing and rendering placeholder content, but it's unclear if ItemSize should also cover widths for items rendered in a grid.

I have a sample 200x200 div as my ItemTemplate pretending to be a Card or Tile, and all items are rendered in a single column.

I also notice that all of my items are contained by a plain `div` with no style, id or other attributes.  If I mark that div as `display: flex; flex-wrap: wrap; justify-content: space-between` then it seems to do as I wish.

Also, I've set specific Style on the BFUList and I'm not seeing that Style applied anywhere.

For reference I'm using `<PackageReference Include="BlazorFluentUI.AllComponents" Version="4.0.2" />`

Thanks and happy new year.

**Comment by DerekChasse** [comment]
Additionally, it seems like the BFUList Razor file is actually a txt file?  Not sure if that's intentional.

https://github.com/BlazorFluentUI/BlazorFluentUI/blob/master/src/BlazorFluentUI.BFUList/BFUList.razor.txt

**Comment by limefrogyank** [comment]
I'm not sure what the behavior of BFUList in grid format would be like.  It probably won't work because it relies on individual item heights for calculating the overall scroll window height.  It can't reduce that scroll height given than some of the items are bunched up on rows.  It might not be completely broken though.  I'm not sure.

As far as where it is coded, that's an old file.  The code is not in any razor file... just the .cs code-behind file.  It shouldn't be partial although that doesn't hurt anything.

**Comment by limefrogyank** [comment]
FYI, you could just use BFUList with the IsVirtualized property off.  Maybe at some point we can fix it for grid layout and then you can turn it on :)

**Comment by DerekChasse** [comment]
From what I can see in their React source they aren't accounting for distinctly sized "Tiles"  If that's what you're referring to.  They seem to force all Tiles to be square, such that their max dimensional size is no larger than, but as close as possible to, some constant.  250px in their case.

Maybe there's something to work off there?

I had thought that they were using CSS `display: grid` in their solution but that doesn't seem to be the case as that would probably greatly complicate things.

**Comment by limefrogyank** [comment]
I originally tried to do virtualization the way the react version did it.  However, it was fairly complicated and the way I was doing it required a lot of interop between blazor and javascript.  So, I settled for a version that wasn’t great…. And then the Blazor team created a `Virtualize` component that I copied.  Essentially, `BFUList` is internally doing the same thing that `Virtualize` does.  Theirs requires a hardcoded height for each item and the scroll window height is calculated based on that height times the number of items in the list.  That's it.  I tweaked this and added a way to measure each virtualized item and average their heights.  This average height is then used to calculate the scroll window height.  As more items are drawn in, I redo the average and adjust the scroll window as necessary.  All the heights are cached.

By comparison, the react component does something similar.  However, they further group items into pages.  For example, there might be 20 items in one page.  The page heights are calculated and the pages are virtualized, not the items.

How this works with a grid might be due to using pages.

**Comment by limefrogyank** [comment]
Hmm... now I wonder if I actually finished that height caching mechanism....

**Comment by limefrogyank** [comment]
Something got broken somewhere...everything is slow.  I need to investigate...

**Comment by limefrogyank** [comment]
Ok, I fixed the demo and it works fine again.  Honestly, this was a big headache when I did it last and I didn't remember how I did it.  I can say that the way the react people are doing their layout is pretty advanced (at least for me).  They're using `float:left` to get their items to do a grid layout... they probably did that instead of using flex for support on IE11 which doesn't have full flex support.

I can try and see if a flex layout will work.  I'll have to play with it a bit.

**Comment by limefrogyank** [comment]
Surprisingly, it took a couple of tweaks and it works... I'll merge it after some more testing.

**Comment by limefrogyank** [comment]
https://github.com/BlazorFluentUI/BlazorFluentUI/commit/f48d4ba7c67c4acbb061b66e25e39ff437d83461

**Comment by DerekChasse** [comment]
Just tried with latest code (4.0.0-CI-20210102-034411) and it works great.

Thanks for this.
