### ISSUE TITLE
Editable Column: DetailsList

### ISSUE THREAD

**Issue by travis-pettry** [BlazorFluentUI/BlazorFluentUI#276]
As a user 
I would like to edit data in my DetailsList
So that I can make changes to tabular data

I have multiple tables of data that require one column to be editable. I have tried to get this to happen via the ColumnTemplate but I cannot get data binding working; I cannot see a way to bind the value of the column to the TextField. 

If this is already possible can you please provide an example?

**Comment by jaisondthomas** [comment]
Hi, I am also looking for a way to do some CRUD operations and inline edit options in the details list. Did you come across any solution or example to do this? Can you please give me a direction on how to go forward with this?

**Comment by limefrogyank** [comment]
There's definitely a problem there.  I think it might have to do with unboxed value variables. I need to test more...

**Comment by jaisondthomas** [comment]
We are using  DetailsList for our new application to do edit and update records. Is there any place I can see an example of how to do this? at https://www.blazorfluentui.net/ link I could not find one.

**Comment by limefrogyank** [comment]
Not yet, but when/if I fix the two way binding issue, I'll add a sample section on custom cells.

**Comment by limefrogyank** [comment]
Yes, there's a flaw with the implementation.  If we pass value types to the DetailsList cells, then they can't be updated because they're copies, not references.  Passing an object would work, but then two-way binding would require an explicit conversion in your own model's getter/setter because you can't bind directly between a string and an object (for example).

I'll have to think about how to make this easier to digest.  Maybe we'll have to wrap the value types in a temporary class.

**Comment by limefrogyank** [comment]
Ok, it's working now.  I pushed a commit that should fix it and there's a new section in the DetailsList demo page that shows how I did it.  (And I don't think I broke anything else.)

I will warn that the performance is not great... but it works.  There's something that is causing the entire list to redraw on every change.  Perhaps you can tune it with some adjustments to the components or maybe it's something internal to DetailsList or DetailsRow.  I'm stopped here for now though...

https://github.com/BlazorFluentUI/BlazorFluentUI/commit/78770b27f1740a7bd28899a5814b8410fe37b927

**Comment by limefrogyank** [comment]
1.  Performance is actually pretty good if you compile the Release version.  The demo runs really well on my PC.
2.  There's a timing issue between updating the model value from the TextField on lost focus and the list updating itself.   If you type something new in one TextField and then immediately click on a different TextField, that will trigger a list refresh and the first TextField gets reset back to what it was before.  It might work better to set it to update on any change rather than lost focus.

**Comment by vnbaaij** [comment]
Added to V5.1
