### ISSUE TITLE
[Discussion] DetailsList two way binding (v5.0 to v5.1)

### ISSUE THREAD

**Issue by sfreudenreich** [BlazorFluentUI/BlazorFluentUI#286]
There is quite a large change when upgrading from 5.0 to 5.1 in regards to the DetailsList.
It is my understanding that it was done to allow for easier property binding but it is quite detrimental to ease of use.

What I would like to see would be that a DetailsRowColumn takes a name and a value provider; or a name and an item template where the item template is given the row item as context.

This would allow one to set up basic text value columns and more complex template columns.

new DetailsRowColumn<MyObject>("My Name") { ColumnItemTemplate = myObject => @<TextField @bind-Value="myObject.Name" /> };
new DetailsRowColumn<MyObject>("ModifiedDate", x => x.ModifiedDate.ToString(DateFormat));

With the changes I can no longer set up basic columns that are not preformatted and the column item template requires using a render fragment builder.

In 5.0 I can achieve 2 way binding in an item template by accessing the row object via it's key so to me this is a step in the wrong direction.

**Comment by limefrogyank** [comment]
It's been a while since I had worked with DetailsList so when I made the change, it was because I could not get two-way property binding to work when basic strings were getting passed by value to the column cells. This seemed the most common way of displaying data using DetailsList.  Your suggestion makes sense though.  When passing objects, it's not a problem.  I'll have to see whether or not I can do both at the same time.

**Comment by limefrogyank** [comment]
This might be an acceptable fix if you want to take a look before we merge it:
https://github.com/BlazorFluentUI/BlazorFluentUI/pull/299

**Comment by limefrogyank** [comment]
https://ambitious-river-018c10b1e-299.westus2.azurestaticapps.net

Has the PR implemented.  I used one line of your code exactly in the demo for `DetailsList`

**Comment by vnbaaij** [comment]
This is merged in now
