### ISSUE TITLE
Broken ValidationSummery after JS Isolation

### ISSUE THREAD

**Issue by SSgumS** [BlazorFluentUI/BlazorFluentUI#315]
Hello
I think after JS isolation on v5.2, some conflicts arose.
I tested `ValidationSummery` (and `FluentUIValidationSummary`) on v5.2.8 and v5.1.0. There was no problem in the earlier one.
When you add a custom error message to form's context and call `NotifyValidationStateChanged`, browser throws an unhandled `System.Text.Json.JsonException: Invalid JSON`.
Log of the error: https://pastebin.com/mVZsPvfX

**Comment by vnbaaij** [comment]
Hi, I appreciate you creating this issue, but the included details on the error do **not** provide any value **at all**. Are you expecting us to go through that line by line? If so, I won't come around to looking at the actual issue until somewhere after the summer, I'm afraid. 

Please remove that part and replace with actual info like: what steps did you take? Does it occur in the demo site? If so, on what page? Etc

**Comment by SSgumS** [comment]
> Hi, I appreciate you creating this issue, but the included details on the error do **not** provide any value **at all**. Are you expecting us to go through that line by line? If so, I won't come around to looking at the actual issue until somewhere after the summer, I'm afraid.
> 
> Please remove that part and replace with actual info like: what steps did you take? Does it occur in the demo site? If so, on what page? Etc

I just added the log for further info. Actually I don't get much useful information from the log myself. Maybe it would be helpful for someone.
I stated steps to reproduce it earlier. Maybe It wasn't much detailed and wasn't clear enough.

Think about something like this:
```
Errors.Add(new FieldIdentifier(EditContext.Model, fieldName: string.Empty), "error description");
EditContext.NotifyValidationStateChanged();
```
In v5.2, ass soon as you call `NotifyValidationStateChanged`, the JsonException will be thrown and validation summery won't get updated.

**Comment by vnbaaij** [comment]
> I just added the log for further info. Actually I don't get much useful information from the log myself. Maybe it would be helpful for someone.

Sorry if I sounded harsh. Wasn't meant to be. The log isn't helpful for anyone. Way too long. Can you edit your post please and remove it. Makes the issue way easier to navigate.

> I stated steps to reproduce it earlier. Maybe It wasn't much detailed and wasn't clear enough.
:
:
I don't think there is such a situation in the demo site. So it should be tested separately.

It is clear what is happening, but it is unclear how to get in that situation in this repo. With what you supplied now, we still need to approximate and go copy/paste etc. to try to get the same outcome. That takes a lot of time.  That is way I ask for steps and if it is happening in demo.. Help us please make it easier to pinpoint the exact repeatable issue. Create a fork of  this repo for example and mutilate a page in the demo so you can link to that page in your copy and can say "look, there is where it goes wrong". Hand us that test, instead of asking us to create it.

Again, I don't want to be harsh or mean. Just asking for a bit more help.

**Comment by SSgumS** [comment]
> > I just added the log for further info. Actually I don't get much useful information from the log myself. Maybe it would be helpful for someone.
> 
> Sorry if I sounded harsh. Wasn't meant to be. The log isn't helpful for anyone. Way too long. Can you edit your post please and remove it. Makes the issue way easier to navigate.
> 
> > I stated steps to reproduce it earlier. Maybe It wasn't much detailed and wasn't clear enough.
> > :
> > :
> > I don't think there is such a situation in the demo site. So it should be tested separately.
> 
> It is clear what is happening, but it is unclear how to get in that situation in this repo. With what you supplied now, we still need to approximate and go copy/paste etc. to try to get the same outcome. That takes a lot of time. That is way I ask for steps and if it is happening in demo.. Help us please make it easier to pinpoint the exact repeatable issue. Create a fork of this repo for example and mutilate a page in the demo so you can link to that page in your copy and can say "look, there is where it goes wrong". Hand us that test, instead of asking us to create it.
> 
> Again, I don't want to be harsh or mean. Just asking for a bit more help.

It's ok. I will try to reproduce it on the demo and update the issue when I had the time.
