### ISSUE TITLE
JS Error when loading DetailsList

### ISSUE THREAD

**Issue by Matthewsre** [BlazorFluentUI/BlazorFluentUI#323]
Having this error when trying to load a DetailsList:

![image](https://user-images.githubusercontent.com/2955659/119710789-a2357300-be13-11eb-934e-8b02be891aeb.png)

![image](https://user-images.githubusercontent.com/2955659/119712662-ae223480-be15-11eb-856f-488f55ae5593.png)

I'll keep trying to figure out if there is anything wrong with my configuration, but wouldn't expect this error in the javascript

**Comment by Matthewsre** [comment]
Found this issue: https://github.com/BlazorFluentUI/BlazorFluentUI/issues/262

Adding this div seems like a workaround for this problem:

![image](https://user-images.githubusercontent.com/2955659/119714380-a95e8000-be17-11eb-831b-f83fb369eba5.png)

I am using 5.3.1 and it looks like this issue still persists

**Comment by limefrogyank** [comment]
I don't have time to look into this too deeply, but if the IntersectionObserver constructor is failing, it's usually because `this.scrollElement` is null or some unsupported element.  (usually null)  However, while it could be because of a missing div with 'data-is-scrollable` attribute (or ancestor div with overflow-y:auto), it might also be some error in the lifecycle creation of DetailsList.  Maybe it is failing in serverside pre-render, maybe it's being disposed before the OnAfterRender method is called where it's needed...  

That's what needs to be checked...

**Comment by Matthewsre** [comment]
> I don't have time to look into this too deeply, but if the IntersectionObserver constructor is failing, it's usually because `this.scrollElement` is null or some unsupported element. (usually null) However, while it could be because of a missing div with 'data-is-scrollable` attribute (or ancestor div with overflow-y:auto), it might also be some error in the lifecycle creation of DetailsList. Maybe it is failing in serverside pre-render, maybe it's being disposed before the OnAfterRender method is called where it's needed...
> 
> That's what needs to be checked...

Thanks for the follow-up, it was the div for this one. Got burned by it earlier and forgot about it when creating another DetailsList. 

Is this div going to continue being a requirement, or will this be something the DetailsList will handle in the future?

**Comment by vnbaaij** [comment]
The div will be a requirement for the forseeable future :(
