### ISSUE TITLE
[Feature Request] OnOpenStateChanged for Dialog

### ISSUE THREAD

**Issue by arshia11d** [BlazorFluentUI/BlazorFluentUI#99]
Hello there!

I started to bring a part of an application to Blazor, of course using your UI library, to get more familiar with Blazor and would like to recommend some features to be developed in the future.

So, first thing that I am missing is an EventCallback in `Dialog` component which notifies me whenever the `IsOpen` property changes. As dialog inherits `Modal`, I think it is supposed to be implemented in `Modal.razor.cs`.

I wish I had more time to directly contribute. 
And I really appreciate your work bringing Fabric components to Blazor!

**Comment by limefrogyank** [comment]
Is `OnDismiss` not enough?  You have to control the state of `IsOpen` yourself and the component only notifies you of internal changes, which can only be that the component wants to be dismissed.  Even the original React version doesn't have an IsOpen callback.  

I think what you are asking for is an `IsOpenChanged` callback so that you can do a `@bind-IsOpen` and have the callback set your isOpen variable automatically.  However, that would not be a great idea for `Dialog` as you'll usually want to run some code in the `OnDismiss` callback that processes whatever inputs you made in the dialog.

Or do I have the wrong idea?

**Comment by 3mo-arshia** [comment]
So I created a new `LoginDialog` which inherits the `Dialog` component class. It lives as a static component in my Navbar and should only be closed and opened ...
I need to send an API call every time the `LoginDialog'`s IsOpen attribute changes to true.
So as I cannot override the IsOpen implementation (which generally doesn't make sense even if I could) I had to implement the logic **externally** in the `Navbar` component and control my `LoginDialog` using extra attributes, which isn't nice because the logic is completely irrelevant to the `Navbar` component and should be implemented internally. So I would rather have an `IsOpenChanged` in my dialog.

Maybe I am missing some feature of Blazor that solves this? ... What do you suggest?

And regarding your question about the conflict between `OnDismiss` and `IsOpenChanged`; I agree .. maybe they should be merged and be controlled using a custom `EventCallback<bool>` or `EventCallback<SomeEnum>` which is triggered every time the `IsOpen` is changed?

I also can provide some sample code until tomorrow If you want me to.

**Comment by limefrogyank** [comment]
@3mo-arshia What immediately comes to mind is instead of inheriting, you could wrap the Dialog with your LoginDialog component.  That way you could have your own IsOpen property with the setter calling your API.   Then all of the code would be inside the LoginDialog.

**Comment by limefrogyank** [comment]
@3mo-arshia Or if you want to use inheritance, just create your own property IsLoginDialogOpen and have the setter both trigger your API and set IsOpen

**Comment by arshia11d** [comment]
Yeah you're right .. I should implement a custom property instead of external implementation...

However I still think that It will get repetitive and not unified in the long run ...
What I mean is that IsOpen stays exposed next to my new custom property, and I would assume that it's not the best practice but rather a work-around which is not a good thing let's say for a larger web app, in which those dialogs are being developed and consumed separately by different developers.
